version: '3.8'
services:
  postgres:
    image: postgres
    container_name: ctuedb
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    # networks:
    #   - ctue-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
      - pgadmin
    volumes:
      - ./src:/app/src
    # networks:
    #   - ctue-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

# networks:
#   ctue-network:
volumes:
  pgdata:
